# Generated by Django 3.2.5 on 2021-07-06 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
                ('contact_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TherapySessions',
            fields=[
                ('session_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('link', models.CharField(max_length=200)),
                ('in_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapy_sessions.therapist')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapy_sessions.therapysessions')),
            ],
        ),
    ]
