# Generated by Django 3.2.5 on 2021-07-07 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('therapy_sessions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='user_id',
        ),
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='therapy_sessions.therapysessions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
