# Generated by Django 3.2.5 on 2021-07-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0002_auto_20210707_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapysessions',
            name='max_members',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
