# Generated by Django 3.2.5 on 2021-07-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0003_therapysessions_max_members'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TherapySessions',
            new_name='TherapySession',
        ),
    ]
