# Generated by Django 3.2.5 on 2021-07-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0004_rename_therapysessions_therapysession'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapysession',
            name='session_title',
            field=models.CharField(default='Session', max_length=200),
            preserve_default=False,
        ),
    ]
