# Generated by Django 3.2.5 on 2021-07-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='Admin', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='has_trigger_warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='likes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
    ]
