# Generated by Django 3.2.5 on 2021-07-08 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210705_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='has_trigger_warning',
            new_name='is_public',
        ),
    ]
