# Generated by Django 3.2.5 on 2021-07-08 15:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210708_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 8, 15, 14, 1, 596080, tzinfo=utc)),
        ),
    ]
