# Generated by Django 3.2.5 on 2021-07-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=10000)),
                ('likes', models.BigIntegerField()),
                ('views', models.BigIntegerField()),
            ],
        ),
    ]
