# Generated by Django 3.2.5 on 2021-07-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone_no', models.CharField(max_length=20)),
                ('category', models.TextField(max_length=1)),
                ('message', models.CharField(max_length=2000)),
            ],
        ),
    ]
