# Generated by Django 3.2.5 on 2021-07-14 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210714_2208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='ContactUsForm',
        ),
    ]
